dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
ruby:
  # build: ./app
  image: narayana-ruby
  dns: 172.17.42.1
  command: bash ./foreman_wrapper.sh
  volumes:
    - ./app:/usr/src/app
  ports:
    - "8081:4567"
  environment:
    - DNSDOCK_NAME=ruby
    - DNSDOCK_IMAGE=bihe
    - WAIT_COMMAND=psql -h postgres.bihe.docker -p 5432 -U postgres --dbname postgres -l
    - WAIT_START_CMD=/usr/local/bundle/bin/foreman start --root /usr/src/app
    - WAIT_SLEEP=2
    - WAIT_LOOPS=10
    - PGPASSWORD=postgres
narayana:
  build: ./wildfly-narayana
  dns: 172.17.42.1
  ports:
    - "8080:8080"
  environment:
    - DNSDOCK_NAME=narayana
    - DNSDOCK_IMAGE=bihe
postgres:
  image: postgres
  dns: 172.17.42.1
  environment:
    - DNSDOCK_NAME=postgres
    - DNSDOCK_IMAGE=bihe
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres