dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
ruby:
  build: ./app
  dns: 172.17.42.1
  volumes:
    - ./app:/usr/src/app
  ports:
    - "8081:4567"
  environment:
    - DNSDOCK_NAME=ruby
    - DNSDOCK_IMAGE=bihe
narayana:
  build: ./wildfly-narayana
  dns: 172.17.42.1
  ports:
    - "8080:8080"
  environment:
    - DNSDOCK_NAME=narayana
    - DNSDOCK_IMAGE=bihe
postgres:
  image: postgres
  dns: 172.17.42.1
  environment:
    - DNSDOCK_NAME=postgres
    - DNSDOCK_IMAGE=bihe
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres